name: postwaremobile 
description: Aplicación PostWare con pantalla de login personalizada

# La siguiente línea define la versión de tu aplicación. +1 en número de versión
# cada vez que subas una actualización a la tienda.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Versión de Dart/Flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Iconos para iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Análisis de código

flutter:
  uses-material-design: true  # Habilita los Material Icons

  # AÑADE ESTA SECCIÓN PARA TUS IMÁGENES (assets)
  assets:
    - lib/assets/images/postware_logo.png  # Ruta exacta de tu logo
    # - assets/images/otra_imagen.png   # Puedes agregar más imágenes aquí

  # fonts:  # Ejemplo de cómo agregar fuentes personalizadas
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf