name: postwaremobile
description: "A new Flutter project."
publish_to: 'none'

# La siguiente línea define la versión de tu aplicación. +1 en número de versión
# cada vez que subas una actualización a la tienda.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'  # Versión de Dart/Flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Iconos para iOS
  http: ^1.1.2  # Añadido para las llamadas HTTP
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  flutter_native_splash: ^2.3.5  # Análisis de código
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/postware_logo.png"

flutter:
  uses-material-design: true  # Habilita los Material Icons

  # AÑADE ESTA SECCIÓN PARA TUS IMÁGENES (assets)
  assets:
    - lib/assets/images/postware_logo.png  # Ruta exacta de tu logo
    # - assets/images/otra_imagen.png   # Puedes agregar más imágenes aquí

  # fonts:  # Ejemplo de cómo agregar fuentes personalizadas
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf